In [11]:
import numpy as np

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

array_2d = np.array([[1,2,3], 
                     [4,5,6]])

#Make arrays using functions
array = np.zeros((3, 4), dtype=np.int16)
print(array)

array_one = np.ones((2, 3, 4))
print(array_one)

#a range - start, end, step
print("Arange")
array_range1 = np.arange(10, 30, 5)
print(array_range1)

array_range2 = np.arange(0, 20, 5)
print(array_range2)

print(array_range1-array_range2)

#linspace - start, end, number of numbers
array_linspace = np.linspace(0, 2, 5)
print("Linspace")
print(array_linspace)

#matrix products
matrix_product1 = np.array([[1,1],
                           [0,1]])
matrix_product2 = np.array([[2,0],
                           [3,4]])
print("Matrix product:")
print(matrix_product1@matrix_product1)

#operators
print("Operators")
print(array1)
array1 *= 3
print(array1)

#Flatten/reshape
print("Flatten/reshape")
print(array_2d.ravel())
print(array_2d.reshape(3,2))
print(array_2d.T)

#Stack
print("Stack")
print(np.vstack((array1, array2)))

#Min, max, standard deviation
print("Min, max, standard deviation")
print(array1.min(), array1.max())

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Arange
[10 15 20 25]
[ 0  5 10 15]
[10 10 10 10]
Linspace
[0.  0.5 1.  1.5 2. ]
Matrix product:
[[1 2]
 [0 1]]
Operators
[1 2 3]
[3 6 9]
Flatten/reshape
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]
Stack
[[3 6 9]
 [4 5 6]]
